# INBUILT

In [ ]:
NumPy 2D array
Send Feedback
Problem Statement:
Given a 2D list, create a numpy 2D array using it.
Note: Given 2D list is [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Print the Numpy array.
Output Format :
numpyArray

In [3]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
li=[[1,2,3],[4,5,6],[7,8,9]]
a=np.array(li)
print(a)

array(['rahul', 'rohan'], dtype='<U5')

In [ ]:
NumPy 0s and 1s
Send Feedback
Problem Statement:
Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
Print the elements of array.
Output Format :
element1 element2 element3 ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np


y = np.arange(10)==4 #Means np.array([int(x==4) for x in range(10)]) where 1,2,3,5,6,7,8,9,10!=4 so False 4==4 so true


x = np.where(np.arange(10)==4,1,0) #Means np.array([int(x==4) for x in range(10)]) where 1,2,3,5,6,7,8,9,10!=4 so False 4==4 so true

for ele in x:
    print(ele,end=" ")

# a=np.zeros( 10,dtype=int)
# a[4]=1
# #print(a)

# for ele in a:
#     print(ele)

# # a=np.zeros(  (1,10),dtype=int   )
# # b=np.zeros(  (1,10),dtype=int   )
# # print(a)

In [ ]:
NumPy Inclusive
Send Feedback
Problem Statement:
Create an array with values ranging consecutively from 9 to 49 (both inclusive).
Print the Numpy array.
Output Format :
element1 element2 element3 ...

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

d=41
a=np.linspace(9,49,num=d,dtype=int)


for ele in a:
    print(ele,end=" ")

In [ ]:
Identity Matrix
Send Feedback
Problem Statement:
Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
Print the Numpy array.
Output Format :
numpyArray

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

a=np.eye(5,6,dtype=int)
print(a)


# for i in range(5):
#     for j in range(6):
#         print(a[i][j],end=" ")
#     print()

In [ ]:
Cut the Rope
Send Feedback
Problem Statement:
You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length.
Note:Array elements are the points where cut is to be made and round upto 2 decimal place.
Print the array element.
Output Format :
element1 
element2 
element3
.

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np

high=5
sample=10

#we know sample size so we use the function linspace.

a=np.linspace(0,5,sample)

for ele in a[1:9]:
    print(round(ele,2))

In [ ]:
Print Elements
Send Feedback
Problem Statement:
Given a 2D integer array size (4, 5) with name input_?
Print elements of highlighted matrix
Alt Text Alt Text Alt Text Alt Text

Output Format :
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .
element1 element2 element3 . . .


In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
input_=np.arange(1,21,1)
input_=input_.reshape(4,5)

#print(_input)



temp= [ input_[2,0:3],(input_[1:4,3]),(input_[2:4,0:5]),(input_[1:3,1:3]) ]

for com in temp[0:2]:
      #print(com)
         for ele in com:
             print(ele,end=" ")
         print()

for com in temp[2:4]:
      #print(com)
         for por in com:
                for ele in por:
                    print(ele,end=" ")
         print()
    

        
        
        
        

print(input_[2][0:3])
print(input_[1:])
print(input_[2:4][0])
print(input_[1:3][1:3])


In [ ]:
Non-Zero elements
Send Feedback
Problem Statemnt:
Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
Print the index of non-zero elements.
Output Format :
index1 index2 index3 ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
li=[1,2,0,0,4,0]

my=np.array(li)

ans=np.where(my!=False)

for ele in ans:
    for ple in ele:
        print(ple,end=" ")

In [ ]:
Multiples of 3
Send Feedback
Problem Statement:
Given an integer array of size 10. Print the index of elements which are multiple of 3.
Note: Generate the following array
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
Print the index of elements.
Output Format :
index1 index2 index3 ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
li=np.arange(1,20,2)


print(np.where(li%3==0))
for ele in np.where(li%3==0)[0]:
    print(ele, end=" ")



In [ ]:
Odd elements
Send Feedback
Problem Statemnt:
Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement secondElement  ... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
li=np.arange(1,11,1)


#print(np.where(li%3==0))
for ele in np.where(li%2==1)[0]:
    li[ele]=-1

    
for ele in li:
    print(ele, end=" ")




In [ ]:
Replace Max
Send Feedback
Problem Statemnt:
Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
Note: Generate the following array
array([11, 2, 13, 4, 15, 6, 27, 8, 19])
Print the Numpy array.
Output Format :
firstElement
secondElement 
... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
li=np.array([11,2,13,4,15,6,27,8,19])


li[(np.argmax(li))]=0
for ele in li:
    print(ele)



In [ ]:
Negate Elements
Send Feedback
Problem Statemnt:
Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
Note: Generate the following array
array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
Print the Numpy array.
Output Format :
firstElement 
secondElement  
... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
li=np.arange(1,11,1)
#print("old",li)

indexreq=

for ele in np.where((li>=3) & (li<9)):
    li[ele]*=-1
for ele in li:
    print(ele)





In [ ]:
Height
Send Feedback
Problem Statemnt:
Given age and height of 20 students in two different numpy arrays with name age and height (in cms). Print the age of those students whose height is above 155 cm.
Print the Numpy array.
Output Format :
age1 height1 
age2 height2 
... 

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])

for ht_index in np.where(height>155)[0]:
    print(age[ht_index],height[ht_index])

In [ ]:
Sort by column
Send Feedback
Problem Statemnt:
Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
That means, we should re-arrange complete row based on 2nd columns' values.
Given 2D array is:
 [[21 20 19 18 17]
  [16 15 14 13 12]
  [11 10  9  8  7]
  [ 6  5  4  3  2]]
Print the 2D array in sorted order.
Note you have to generate the 2D Array.Here 2nd column means column present at index 1.
Output Format :
[[ 6  5  4  3  2]
[11 10  9  8  7]
[16 15 14 13 12]
[21 20 19 18 17]]

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format





#https://www.geeksforgeeks.org/numpy-argsort-in-python/
import numpy as np

ni=[  [21,20,19,18,17],
      [16,15,14,13,12],
      [11,10,9,8,7],
      [6,5,4,3,2] 
   ]

n=np.array(ni)

#argsort() returns index in that order which would sort the array as per requiremenet.

new_array=n[   n[:,1].argsort()]
print(new_array)


        
        
        
    



In [ ]:
Killed in USA
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find value of killed column only where country == ‘United States’?
Print 0 in place of missing values.
Print count of Killed as integer value.
Output Format :
Killed1
Killed2
Killed3
Killed4
. . .
. . .
. . .

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format
import csv
import numpy as np
with open('terrorismData.csv') as file:
    main_file=csv.DictReader(file,skipinitialspace=True)
    
    li=list(main_file) 
    uscountry=[]
    
    killed=[]
    
    ans=[]
    
    for row in li:
         uscountry.append(row['Country'])
         killed.append(row['Killed'])
        
    '''
         if row['Country']=='United States':
                if row['Killed']!='':
                    ans.append(float(row['Killed']))
                else:
                    ans.append(0)
                    
    for ele in ans:
        print(int(ele))
    
    '''
        
        
uscountry=np.array(uscountry)
killed=np.array(killed)
boolean_array=uscountry=='United States'

killedus=killed[boolean_array] #people killed in US in str.
#################################################


killedus[killedus==""]=0

killedus=np.array(killedus,dtype=float)
killedus=np.array(killedus,dtype=int)

#ans=killedus.sum()
#'''
#print(ans)
for ele in killedus:
    print(ele)
    


In [ ]:
Total Killed in USA
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find total number of people killed from USA?
Note: Some columns of killed are empty so replace them by 0.
Print count of Killed as integer value.
Output Format :
TotalKilled

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format

import csv
import numpy as np


with open('terrorismData.csv') as file:
    main_file=csv.DictReader(file,skipinitialspace=True)
    
    killed=[]
    
    for row in main_file:
        if row['Country']=='United States':
            killed.append(row['Killed'])

killed=np.array(killed)

killed[killed==""]=0

killed=np.array(killed,dtype=float)

ans=killed.sum()
print(int(ans))

            
    
    
    
    


# ASSIGNMENT

In [2]:
https://www.kaggle.com/code/singhparikshit/terriorism-dataset-analysis

SyntaxError: invalid syntax (<ipython-input-2-9281bf3fc23b>, line 1)

In [ ]:
Terrorism Day
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the number of attack held between day 10 and day 20?(ignoring the year and month)(including both day)
Print count of NumberOFAttack as integer value.
Output Format :
count

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format

import csv
import numpy as np


with open('terrorismData.csv') as file:
    main_file=csv.DictReader(file,skipinitialspace=True)
    
    attack=[]
    
    for row in main_file:
        #if (float(row['Day'])>=(10) and float(row['Day'])<21):
            attack.append(row['Day'])
            
    attack=np.array(attack,dtype=float)
    
    ans=attack[ (attack>=10) & (attack<21)]
    
    #print(len(ans))
    #or 
    print(ans.shape[0])
    
    
        
    
    
    


In [ ]:
Terrorism Date
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the number of attack held between 1 Jan 2010 and 31 Jan 2010?(including both date).
Note Ignore the case where day is 0
Print count of NumberOFAttack as integer value.
Output Format :
count

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format

import csv
import numpy as np


with open('terrorismData.csv') as file:
    main_file=csv.DictReader(file,skipinitialspace=True)
    
    attack=[]#array of days.
    
    
    
    
    for row in main_file:
  
            attack.append([row['Day'],row['Month'],row['Year']])
      
        
    
    attack=np.array(attack,dtype=float)
    
    #print(attack) nx3 array
    
    attack=attack[attack[:,2]==2010]
    attack=attack[attack[:,1]==1]
    attack=attack[attack[:,0]>=1]
    
    #ans=attack[ (attack>=1) & (attack<32)]
    
    #print(len(ans))
    #or 
    print(attack.shape[0])
    #'''
    
    
        
    
    
    


In [ ]:
Terror Casualty Attack
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
As we knew the Kargil ( in Jammu and Kashmir) War that took place between May 1999 and July 1999 (3 Months) ,so there was a huge conflict in Kashmir Valley during this period.
In this dataset, there is no information regarding the war between the two countries to find out the casualty during the war.
So find out the attack in this period in which maximum casualties happened.
Print the count of casualties (as integer), city in which that attack happened and name of attack group.
Note : Casualty = Killed + Wounded.Fill the empty value in killed or wounded feature to 0.
Output Format :
Casualty City TerroristGroup

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format\
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format

import csv
import numpy as np
'''

with open('terrorismData.csv') as file:
    main_file=csv.DictReader(file,skipinitialspace=True)
    
    
        
    attack=[]#array of days.
    
    
    details=[]
    
    for row in main_file:
        attack.append( [row['Month'],row['Year'],row['Killed'],row['Wounded'],row['Wounded'] ])
        details.append( [row['City'],row['Group'] ] )
      
        
    
    
    
    
    
    attack=np.array(attack)
    
   
    
    #print(len(details),len(attack))
    
    
    
    
    
    attack[ (attack[:,2]=='')]='0'
    attack[ (attack[:,3]=='')]='0'
    
    attack[ (attack[:,4]=='')]='0'
    
    
    
    attack=np.array(attack,dtype=float)
    #################################################################################################################
    details=np.array(details,dtype='<U5')
    #################################################################################################################
    
    
    
    ans=attack[:,1]==1999 #prints bools of t and f row-wise where for each row., col[1] is 1999
    #Here, total length is number of rows.
    #print(len(ans))
    
    
    
    
    #################################################################################################################
    details=details[ans] #This is done to remove thee waste entries of city and group for which year is not 1999
    ##################################################################################################################
    attack=attack[attack[:,1]==1999] 
    
    #print(len(details),len(attack)):same
    
    
    
    

    
    
    
                    #when condition is true, whole row becomes true, rest are false
    requiredarea=(attack[:,0]>=5) & (attack[:,0]<8)  
    attack=attack[ requiredarea]  #prints the rows for which the above condition on col0 is true.
    
    
    
    #####################
    details=details[requiredarea]
    ########################
    
    
    
    #print(len(details),len(attack)):same
  
    
    
    
    
    
    
    
    
    
    
    attack=np.array(attack,dtype=int)
    
    attack[:,4]=attack[:,2]+attack[:,3]
    
    
    
    
    index_with_max_cas=(attack[:,4].argmax()) #prints index of row wih max casualties. This index is without any removal of
                                              # row in which "" was there. So len(attack) is same as that of main_file
    
    maxcasuality=attack[index_with_max_cas][4]
    
    
    
    #maxcasuality=attack[:,4].max()
    
    
    #print(maxcasuality)
    

    
    #print(len(details),len(attack))
    
    
    
    
    
    index=index_with_max_cas
    
    #print(details[1][0])
    #print(attack[191][:],"lol",details[191,:])
    
    
    city=(details[index,0])
    
    group=details[index,1]
    
    print(maxcasuality,"Unknown","Unknown")
    
    '''
    
    
    
with open("terrorismData.csv") as file:
    file_obj = csv.DictReader(file,skipinitialspace = False)
    killed = []
    wounded = []
    month = []
    year = []
    city = []
    group = []
    
    for row in file_obj:
        if "1999" in row["Year"]:
            if "5" in row["Month"] or  "6" in row["Month"] or "7" in row["Month"]:
                if "Unknown" not in row["City"]:
                    if "Unknown" not in row["Group"]:
                        if "Jammu and Kashmir" in row["State"]:
                            killed.append(row["Killed"])
                            wounded.append(row["Wounded"])
                            city.append(row["City"])
                            group.append(row["Group"])
        
    killed = np.array(killed)
    wounded = np.array(wounded)
    city = np.array(city)
    group = np.array(group)
    
    killed_bool = killed == ""
    wounded_bool = wounded == ""
    
    killed[killed_bool] = "0.0"
    wounded[wounded_bool] = "0.0"
    
    killed = np.array(killed, dtype = float)
    wounded = np.array(wounded, dtype = float)
    
    casualty = (killed + wounded)
    max_casualty = (int)(casualty.max())
    max_casualty_arg = casualty.argmax()
    print(max_casualty,city[max_casualty_arg],group[max_casualty_arg])
    
    
    
    
    
    


In [ ]:
Terror Casualty Red
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the casualty in the Red Corridor States ? Mainly Red corridor states include Jharkhand, Odisha, Andhra Pradesh, and Chhattisgarh.
Note: Casualty=Killed +Wounded
Print count of Casualty as integer value.
Output Format :
Count

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
import csv
import numpy as np


with open('terrorismData.csv') as file:
    main_file=csv.DictReader(file,skipinitialspace=True)
    
    
        
    attack=[]#array of days.
    
    
    
    
    for row in main_file:
        #attack.append( [row['Month'],row['Year'],row['Killed'],row['Wounded'],row['Wounded'] ])
        #details.append( [row['City'],row['Group'] ] )
        
        state=row['State']
        if state=='Jharkhand' or state=='Odisha' or state=='Andhra Pradesh' or state=='Chhattisgarh':
            attack.append([row['Killed'],row['Wounded'],row['Wounded']])      
        
    
    
    attack=np.array(attack)#bydefault
    attack[attack==""]='0'
    
    
    attack=np.array(attack,dtype=float)
    attack[:,2]=(attack[:,0]+attack[:,1])
    
    attack=np.array(attack,dtype=int)#bydefault
    
    print(attack[:,2].sum())
    
    #print(5628)
    
    
    
    
    
    
    
    
    
    

In [ ]:
Terror City Casualty
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find top 5 Indian Cities which has most number of casualties ?
Print top 5 cities along with total casualties in that city. Print count of Casualty as integer value.
Note: Ignoring the City which is Unknown.
Casualty = Killed + Wounded.
Output Format :
city_1 casualty_1
city_2 casualty_2
city_3 casualty_3
city_4 casualty_4
city_5 casualty_5

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format
import csv
import numpy as np

with open('terrorismData.csv') as file:
    main_file=csv.DictReader(file,skipinitialspace=True)
    
    
        
    attack=[]#array of days.
    
    
    
    c=[]
    cit=[]
    k=[]
    w=[]
    for row in main_file:      
        country=row['Country']
        if country=='India' and row['City']!='Unknown':
            attack.append([row['Killed'],row['Wounded']])
                           
            k.append(row['Killed'])
            w.append(row['Wounded'])
            cit.append(row['City'])
        
    
    #c=np.array(c)
    k=np.array(k)
    w=np.array(w)
    ci=np.array(cit)
    
    k[k=='']='0.0'                    
    w[w=='']='0.0'
    
    k=np.array(k,dtype=float)
    w=np.array(w,dtype=float)
    c=np.array(k+w,dtype=int)
    
    #print(c)
    #print(c.max())
    
    dic={}
    for i in range(len(ci)):
        if ci[i] in dic:
            dic[ ci[i] ]+=c[i]
        else:
            dic[ci[i] ]=c[i]
            
            
    for i in range(5):    
        maxvalue=max(dic.values())
    ###############################################################
        maxkey=[key for key in dic if dic[key]==maxvalue]
    ####################################################
        print(maxkey[0],maxvalue)
        
        dic[maxkey[0]]=-1*10000
    
   
    
    
    
    
    
    
    
    

In [ ]:
Terrorism FrequentDay
Send Feedback
Given file "terrorismData.csv"
It is an open-source database including information on terrorist attacks around the world from 1970 through 2017. This dataset includes systematic data on domestic as well as international terrorist incidents that have occurred during this time period
Problem Statement :
Find the most frequent day of attack in a terrorismDataset ?
Note: Here np.unique can be used.
Print count of frequent day and number of attack as Integer value.
Output Format :
Day NumberOFAttack

In [ ]:
## Open and read data file as specified in the question
## Print the required output in given format## Open and read data file as specified in the question
## Print the required output in given format
## Open and read data file as specified in the question
## Print the required output in given format
import csv
import numpy as np

with open('terrorismData.csv') as file:
    file_data=csv.DictReader(file,skipinitialspace=True)
    
    #file_data=csv.DictReader(file_obj, skipinitialspace=True)
    
    day=[]
    for row in file_data:
        day.append(row['Day'])
    np_day=np.array(day, dtype='int')
    
    day, count=np.unique(np_day, return_counts=True)
    print(day[np.argmax(count)], count[np.argmax(count)])
   
    
    
    
    
    
    
    
    